# Generated by Django 5.1.7 on 2025-03-18 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business_line', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('registration_step', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FallbackNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('reason', models.CharField(blank=True, help_text='Reason for transferring the call', max_length=255, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallback_numbers', to='gabby_booking.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ExceptionalClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptional_closings', to='gabby_booking.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('hours_type', models.CharField(choices=[('closed', 'Closed'), ('open_24', 'Open 24 Hours'), ('custom', 'Custom Hours')], default='custom', max_length=10)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='gabby_booking.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('voice_type', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='gabby_booking.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='gabby_booking.organization')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='gabby_booking.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_choice', models.CharField(choices=[('sms', 'SMS'), ('google_calendar', 'Google Calendar')], max_length=50)),
                ('cutoff_time', models.TimeField()),
                ('allow_modifications', models.BooleanField(default=True)),
                ('modification_deadline', models.TimeField(blank=True, null=True)),
                ('allow_cancellations', models.BooleanField(default=True)),
                ('cancellation_deadline', models.TimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_types', to='gabby_booking.organization')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleCalendarSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_calendar_id', models.CharField(max_length=255)),
                ('message_template', models.TextField(help_text='Write the message that will be sent with the Google Calendar invite. Make sure to include your booking link.')),
                ('reservation_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_settings', to='gabby_booking.reservationtype')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('details', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='gabby_booking.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('details', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='gabby_booking.organization')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='gabby_booking.service')),
            ],
        ),
        migrations.CreateModel(
            name='SMSSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_template', models.TextField(help_text='Write the SMS that Gabby will send during the call. Make sure to include your booking link.')),
                ('reservation_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_settings', to='gabby_booking.reservationtype')),
            ],
        ),
    ]
