# Generated by Django 5.1.7 on 2025-03-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabby_booking', '0002_organization_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesshours',
            name='break_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='break_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
