# Generated by Django 5.1.7 on 2025-03-22 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabby_booking', '0003_businesshours_break_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prompt', to='gabby_booking.organization')),
            ],
        ),
    ]
