# Generated by Django 5.2.7 on 2025-10-17 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabby_booking', '0004_organizationprompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='details',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='registration_step',
            new_name='current_step',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='details',
            new_name='detail',
        ),
        migrations.RemoveField(
            model_name='option',
            name='service',
        ),
        migrations.AddField(
            model_name='option',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='options', to='gabby_booking.service'),
        ),
        migrations.AddField(
            model_name='organization',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='business_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('one-main', 'Only one main address'), ('multiple-locations', 'Multiple locations or rooms'), ('client-location', "At client's location")], max_length=20)),
                ('main_address', models.TextField(blank=True, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_location', to='gabby_booking.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('image', models.TextField(blank=True, null=True)),
                ('service_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='gabby_booking.servicelocation')),
            ],
        ),
    ]
