# Generated by Django 5.2.7 on 2025-10-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabby_booking', '0005_rename_details_option_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='booking_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='use_integrated_booking',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='use_phone_service',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
