# Generated by Django 5.2.7 on 2025-10-17 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabby_booking', '0006_organization_booking_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesshours',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='gabby_booking.location'),
        ),
        migrations.AddField(
            model_name='exceptionalclosing',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exceptional_closings', to='gabby_booking.location'),
        ),
    ]
