# Generated by Django 5.2.7 on 2025-10-17 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabby_booking', '0007_businesshours_location_exceptionalclosing_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAddOnConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propose_addons', models.BooleanField(default=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addon_config', to='gabby_booking.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('profile_image', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='gabby_booking.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='gabby_booking.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMemberConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_multiple_members', models.BooleanField(default=False)),
                ('allow_staff_self_manage', models.BooleanField(default=False)),
                ('allow_client_choose_worker', models.BooleanField(default=False)),
                ('auto_assign_bookings', models.BooleanField(default=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_config', to='gabby_booking.organization')),
            ],
        ),
    ]
