# Generated by Django 5.2.7 on 2025-10-17 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabby_booking', '0008_serviceaddonconfig_teammember_teammemberconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_cutoff_time', models.BooleanField(default=False)),
                ('cutoff_time_value', models.CharField(blank=True, help_text="e.g., '15 minutes before', '1 hour before'", max_length=50, null=True)),
                ('set_minimum_gap', models.BooleanField(default=False)),
                ('gap_time_value', models.CharField(blank=True, help_text="e.g., 'No gap', '15 minutes', '1 hour'", max_length=50, null=True)),
                ('allow_modifications', models.BooleanField(default=True)),
                ('modifications_deadline', models.CharField(blank=True, help_text='Deadline before appointment', max_length=50, null=True)),
                ('allow_cancellations', models.BooleanField(default=True)),
                ('cancellation_deadline', models.CharField(blank=True, help_text='Deadline before appointment', max_length=50, null=True)),
                ('email_reminder_delay', models.CharField(blank=True, help_text='When to send reminder before appointment', max_length=50, null=True)),
                ('offer_newsletter', models.BooleanField(default=False)),
                ('terms_and_conditions_url', models.URLField(blank=True, max_length=500, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_rule', to='gabby_booking.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_sms_content', models.TextField(help_text='SMS sent by Gabby to clients with booking link')),
                ('confirmation_email_subject', models.CharField(default='Your appointment is confirmed ✅', max_length=255)),
                ('confirmation_email_content', models.TextField(help_text='Email sent after booking confirmation')),
                ('modification_email_subject', models.CharField(default='Your appointment has been updated ✅', max_length=255)),
                ('modification_email_content', models.TextField(help_text='Email sent after appointment modification')),
                ('cancellation_email_subject', models.CharField(default='Your appointment has been canceled ❌', max_length=255)),
                ('cancellation_email_content', models.TextField(help_text='Email sent after appointment cancellation')),
                ('reminder_email_subject', models.CharField(default='Reminder - Your appointment is coming up 📅', max_length=255)),
                ('reminder_email_content', models.TextField(help_text='Reminder email sent before appointment')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_template', to='gabby_booking.organization')),
            ],
        ),
    ]
