# Generated by Django 5.2.7 on 2025-10-17 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabby_booking', '0009_bookingrule_communicationtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='greeting_message',
            field=models.TextField(blank=True, help_text='First sentence when assistant picks up', null=True),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant', to='gabby_booking.organization'),
        ),
    ]
