# Generated by Django 5.2.7 on 2025-10-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabby_booking', '0010_assistant_greeting_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assistant',
            name='twilio_phone_number',
            field=models.CharField(blank=True, help_text='Dedicated Twilio phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='twilio_phone_sid',
            field=models.CharField(blank=True, help_text='Twilio phone number SID', max_length=100, null=True),
        ),
    ]
