# Generated by Django 5.2.7 on 2025-10-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabby_booking', '0011_assistant_is_active_assistant_twilio_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='assistant_created',
            field=models.BooleanField(default=False),
        ),
    ]
