# Generated by Django 5.2.7 on 2025-10-19 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabby_booking', '0012_organization_assistant_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='gabby_booking.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.PositiveIntegerField(help_text='Total duration in minutes (service + options)')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price (service + options)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, default='', help_text='Customer notes from booking')),
                ('internal_notes', models.TextField(blank=True, default='', help_text='Internal staff notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='gabby_booking.location')),
                ('options', models.ManyToManyField(blank=True, related_name='appointments', to='gabby_booking.option')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='gabby_booking.organization')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_as_provider', to='gabby_booking.teammember')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='gabby_booking.service')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='gabby_booking.customer')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'email'], name='gabby_booki_organiz_683705_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('organization', 'email')},
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['organization', 'date', 'status'], name='gabby_booki_organiz_aa92c2_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['customer', '-date'], name='gabby_booki_custome_4fcdc8_idx'),
        ),
    ]
